### ISSUE TITLE
Issues with Visibility of Username And Password ! 

### ISSUE THREAD

**Issue by DanBrown47** [AswinAsok/InstaFetcher#1]
There is a [DotEnv Library ](https://pypi.org/project/python-dotenv/)which can be used to store the Username and Password, Also There is no Input of username or Password in the `uspass.py`

This can also trigger a security vulnerability and sub-standard coding methedology. 

Also this code dosen`t trigger itself into asking for Username or password before hand !

**Comment by AswinAsok** [comment]
Make a pull request I will look forward to it.

**Comment by AswinAsok** [comment]
Create a pull request regarding the changes which are to made and I will look forward to it as soon as possible 😊.

**Comment by DanBrown47** [comment]
Hi I have created a PR do Check it out !! I have not tested it because I don`t use Instagram

**Comment by AswinAsok** [comment]
It is working fine but here

USERNAME = os.getenv("USERNAME")
PASSWORD = os.getenv("PASSWORD")

getenv is importing windows Username 

Even through I gave my Instausername in .env while running it changes

**Comment by AswinAsok** [comment]
Can you change the variable name in .env from USERNAME and PASSWORD to InstaUsername and InstaPassword

**Comment by AswinAsok** [comment]
Thanks for the help😊.
